name: bencode
version: 0.0.4
author: Daniel Lundqvist <daniel.lundqvist84@gmail.com>
description: A Bencode decoder and encoder library ported to dart with node-bencode as inspiration.
homepage: https://github.com/dlq84/dart-bencode
documentation: https://github.com/dlq84/dart-bencode/blob/master/README.md

environment:
  sdk: ">=2.2.2<3.0.0"

dev_dependencies:
  test: ^1.9.4
